In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R

BbarN = np.array([[0.969846, 0.17101, 0.173648],
                  [-0.200706, 0.96461, 0.17101],
                  [-0.138258, -0.200706, 0.969846]])

BNtrue = np.array([[0.963592, 0.187303, 0.190809],
                   [-0.223042, 0.956645, 0.187303],
                   [-0.147454, -0.223042, 0.963592]])

BbarB = np.dot(BbarN, BNtrue.T)

def C2PRV(C):
    r = R.from_matrix(C)
    return r.as_rotvec()

p = C2PRV(BbarB)
angle_deg = np.linalg.norm(p) * 180 / np.pi

print("BbarB:")
print(BbarB)
print("PRV (Axis-angle representation):")
print(p)
print("Angle in degrees:")
print(angle_deg)


BbarB:
[[ 0.99970013 -0.02019574 -0.01382426]
 [ 0.0199059   0.99958589 -0.02076977]
 [ 0.01423821  0.02048801  0.99968841]]
PRV (Axis-angle representation):
[ 0.02063242 -0.01403363  0.02005425]
Angle in degrees:
1.8341922519300204
